name: "Run validation and upload results"
description: "Run validation script and upload the results to be commented on the PR"
inputs:
    target-file:
        description: "File to write outputs"
        required: false
        default: "validate-results.md"
    repo:
        description: "The repo"
        required: true
    pr-number:
        description: "The PR number"
        required: true
    token:
        description: "GitHub Token"
        required: true
    user:
        description: "The PR submitter to tag"
        required: true
runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v6

        - uses: actions/setup-python@v6
          with:
              python-version: "3.14"
              cache: "pip"
              python-version-file: ".python-version"

        - name: Install uv
          uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

        - name: Extract the new plugin data and lint it
          shell: bash
          run: |
              set -ex  # fail script on first command failure.

              scripts/validateall.sh "${{ inputs.target-file }}"

        - name: Record additional context for later comment
          shell: bash
          if: always()
          run: |
              mkdir pr-data
              echo ${{ inputs.pr-number }} > pr-data/pr-num.txt
              echo ${{ inputs.user }} > pr-data/pr-author.txt
              cp "${{ inputs.target-file }}" pr-data/

        - name: Upload artifact
          env:
              GITHUB_TOKEN: ${{ inputs.token }}
          if: always()
          uses: actions/upload-artifact@v7
          with:
              path: pr-data
