name: "Validate new plugin"

on:
    pull_request:
        types: [opened, reopened]
        paths:
            - 'plugins.json'
    push:
        paths:
            - 'plugins.json'
            - '.github/workflows/plugin-pr-validate.yml'
            - 'scripts/lint-metadata.py'
            - 'scripts/extract-modified-json.py'
            - 'scripts/validateall.sh'

permissions:
    contents: read
    pull-requests: write

jobs:
    plugin-validation-pr:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v6
          - name: Run validation
            uses: ./.github/actions/plugin_pr_validate
            with:
                pr-number: ${{ github.event.number }}
                token: ${{ github.token }}
                user: ${{ github.event.pull_request.user.login }}
